defaults:
  - base
  - _self_

_target_: icl_lm.models.ICL
name: icl

icl_use_wv: false
icl_use_skip_mlp: false
icl_use_ln: true
icl_use_rotary_embedding: false

share_covariate_attn: false
share_covariate_mlp: false

share_icl_attn: false
share_icl_mlp: false

use_mlp_out: false

block_order: null
