defaults:
  - transformer_medium
  - _self_

_target_: icl_lm.models.ReducedTransformerFast
name: reduced_transformer_medium_fast

# To keep parameter count consistent
n_layers: 24

hidden_dim: 1024
embed_dim: 1024
mlp_dim: 1024