defaults:
  - model: transformer_small
  - training: base
  - generation: base
  - dataset: tinystories
  - visualization: base
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

mode: train
device: cuda:0
